clock = "$CLOCK"
static = true

[options]
ROM = "wozmon.bin"
CLOCK = "1M"

[[region]]
type = "rom"
source = "$ROM"
match = 0xFF00
match_mask = 0xFF00
address_mask = 0x7FFF

[[region]]
type = "acia"
match = 0xFE00
match_mask = 0xFF00
address_mask = 0x0003
ocrcrlf = true
ctrl-c = "reset"

[[region]]
type = "ram"
nv = true
file = "nvram0.img"
size = 0x4000
match = 0x4000
match_mask = 0xC000
address_mask = 0x3FFF

[[region]]
type = "ram"
size = 0x4000
match = 0x0000
match_mask = 0xC000
address_mask = 0x3FFF
