instructions = {
        # Low nibble 0x0
        0x00: ("BRK", "implied"),
        0x10: ("BPL", "relative"),
        0x20: ("JSR", "absolute"),
        0x30: ("BMI", "relative"),
        0x40: ("RTI", "implied"),
        0x50: ("BVC", "relative"),
        0x60: ("RTS", "implied"),
        0x70: ("BVS", "relative"),
        0x80: ("BRA", "relative"),
        0x90: ("BCC", "relative"),
        0xA0: ("LDY", "immediate"),
        0xB0: ("BCS", "relative"),
        0xC0: ("CPY", "immediate"),
        0xD0: ("BNE", "relative"),
        0xE0: ("CPX", "immediate"),
        0xF0: ("BEQ", "relative"),

        # Low nibble 0x1
        0x01: ("ORA", "indirect_X"),
        0x11: ("ORA", "indirect_Y"),
        0x21: ("AND", "indirect_X"),
        0x31: ("AND", "indirect_Y"),
        0x41: ("EOR", "indirect_X"),
        0x51: ("EOR", "indirect_Y"),
        0x61: ("ADC", "indirect_X"),
        0x71: ("ADC", "indirect_Y"),
        0x81: ("STA", "indirect_X"),
        0x91: ("STA", "indirect_Y"),
        0xA1: ("LDA", "indirect_X"),
        0xB1: ("LDA", "indirect_Y"),
        0xC1: ("CMP", "indirect_X"),
        0xD1: ("CMP", "indirect_Y"),
        0xE1: ("SBC", "indirect_X"),
        0xF1: ("SBC", "indirect_Y"),

        # Low nibble 0x2
        0x12: ("ORA", "zp_indirect"),
        0x32: ("AND", "zp_indirect"),
        0x52: ("EOR", "zp_indirect"),
        0x72: ("ADC", "zp_indirect"),
        0x92: ("STA", "zp_indirect"),
        0xA2: ("LDX", "immediate"),
        0xB2: ("LDA", "zp_indirect"),
        0xD2: ("CMP", "zp_indirect"),
        0xF2: ("SBC", "zp_indirect"),

        # Low nibble 0x4
        0x04: ("TSB", "zeropage"),
        0x14: ("TRB", "zeropage"),
        0x24: ("BIT", "zeropage"),
        0x34: ("BIT", "zeropage_X"),
        0x64: ("STZ", "zeropage"),
        0x74: ("STZ", "zeropage_X"),
        0x84: ("STY", "zeropage"),
        0x94: ("STY", "zeropage_X"),
        0xA4: ("LDY", "zeropage"),
        0xB4: ("LDY", "zeropage_X"),
        0xC4: ("CPY", "zeropage"),
        0xE4: ("CPX", "zeropage"),

        # Low nibble 0x5
        0x05: ("ORA", "zeropage"),
        0x15: ("ORA", "zeropage_X"),
        0x25: ("AND", "zeropage"),
        0x35: ("AND", "zeropage_X"),
        0x45: ("EOR", "zeropage"),
        0x55: ("EOR", "zeropage_X"),
        0x65: ("ADC", "zeropage"),
        0x75: ("ADC", "zeropage_X"),
        0x85: ("STA", "zeropage"),
        0x95: ("STA", "zeropage_X"),
        0xA5: ("LDA", "zeropage"),
        0xB5: ("LDA", "zeropage_X"),
        0xC5: ("CMP", "zeropage"),
        0xD5: ("CMP", "zeropage_X"),
        0xE5: ("SBC", "zeropage"),
        0xF5: ("SBC", "zeropage_X"),

        # Low nibble 0x6
        0x06: ("ASL", "zeropage"),
        0x16: ("ASL", "zeropage_X"),
        0x26: ("ROL", "zeropage"),
        0x36: ("ROL", "zeropage_X"),
        0x46: ("LSR", "zeropage"),
        0x56: ("LSR", "zeropage_X"),
        0x66: ("ROR", "zeropage"),
        0x76: ("ROR", "zeropage_X"),
        0x86: ("STX", "zeropage"),
        0x96: ("STX", "zeropage_Y"),
        0xA6: ("LDX", "zeropage"),
        0xB6: ("LDX", "zeropage_Y"),
        0xC6: ("DEC", "zeropage"),
        0xD6: ("DEC", "zeropage_X"),
        0xE6: ("INC", "zeropage"),
        0xF6: ("INC", "zeropage_X"),

        # Low nibble 0x7
        0x07: ("RMB0", "zeropage"),
        0x17: ("RMB1", "zeropage"),
        0x27: ("RMB2", "zeropage"),
        0x37: ("RMB3", "zeropage"),
        0x47: ("RMB4", "zeropage"),
        0x57: ("RMB5", "zeropage"),
        0x67: ("RMB6", "zeropage"),
        0x77: ("RMB7", "zeropage"),
        0x87: ("SMB0", "zeropage"),
        0x97: ("SMB1", "zeropage"),
        0xA7: ("SMB2", "zeropage"),
        0xB7: ("SMB3", "zeropage"),
        0xC7: ("SMB4", "zeropage"),
        0xD7: ("SMB5", "zeropage"),
        0xE7: ("SMB6", "zeropage"),
        0xF7: ("SMB7", "zeropage"),

        # Low nibble 0x8
        0x08: ("PHP", "implied"),
        0x18: ("CLC", "implied"),
        0x28: ("PLP", "implied"),
        0x38: ("SEC", "implied"),
        0x48: ("PHA", "implied"),
        0x58: ("CLI", "implied"),
        0x68: ("PLA", "implied"),
        0x78: ("SEI", "implied"),
        0x88: ("DEY", "implied"),
        0x98: ("TYA", "implied"),
        0xA8: ("TAY", "implied"),
        0xB8: ("CLV", "implied"),
        0xC8: ("INY", "implied"),
        0xD8: ("CLD", "implied"),
        0xE8: ("INX", "implied"),
        0xF8: ("SED", "implied"),

        # Low nibble 0x9
        0x09: ("ORA", "immediate"),
        0x19: ("ORA", "absolute_Y"),
        0x29: ("AND", "immediate"),
        0x39: ("AND", "absolute_Y"),
        0x49: ("EOR", "immediate"),
        0x59: ("EOR", "absolute_Y"),
        0x69: ("ADC", "immediate"),
        0x79: ("ADC", "absolute_Y"),
        0x89: ("BIT", "immediate"),
        0x99: ("STA", "absolute_Y"),
        0xA9: ("LDA", "immediate"),
        0xB9: ("LDA", "absolute_Y"),
        0xC9: ("CMP", "immediate"),
        0xD9: ("CMP", "absolute_Y"),
        0xE9: ("SBC", "immediate"),
        0xF9: ("SBC", "absolute_Y"),

        # Low nibble 0xA
        0x0A: ("ASL", "accumulator"),
        0x1A: ("INA", "implied"),
        0x2A: ("ROL", "accumulator"),
        0x3A: ("DEA", "implied"),
        0x4A: ("LSR", "accumulator"),
        0x5A: ("PHY", "implied"),
        0x6A: ("ROR", "accumulator"),
        0x7A: ("PLY", "implied"),
        0x8A: ("TXA", "implied"),
        0x9A: ("TXS", "implied"),
        0xAA: ("TAX", "implied"),
        0xBA: ("TSX", "implied"),
        0xCA: ("DEX", "implied"),
        0xDA: ("PHX", "implied"),
        0xEA: ("NOP", "implied"),
        0xFA: ("PLX", "implied"),

        # Low nibble 0xB
        0xCB: ("WAI", "implied"),
        0xDB: ("STP", "implied"),

        # Low nibble 0xC
        0x0C: ("TSB", "absolute"),
        0x1C: ("TRB", "absolute"),
        0x2C: ("BIT", "absolute"),
        0x3C: ("BIT", "absolute_X"),
        0x4C: ("JMP", "absolute"),
        0x6C: ("JMP", "indirect"),
        0x7C: ("JMP", "abs_indirect_X"),
        0x8C: ("STY", "absolute"),
        0x9C: ("STZ", "absolute"),
        0xAC: ("LDY", "absolute"),
        0xBC: ("LDY", "absolute_X"),
        0xCC: ("CPY", "absolute"),
        0xEC: ("CPX", "absolute"),

        # Low nibble 0xD
        0x0D: ("ORA", "absolute"),
        0x1D: ("ORA", "absolute_X"),
        0x2D: ("AND", "absolute"),
        0x3D: ("AND", "absolute_X"),
        0x4D: ("EOR", "absolute"),
        0x5D: ("EOR", "absolute_X"),
        0x6D: ("ADC", "absolute"),
        0x7D: ("ADC", "absolute_X"),
        0x8D: ("STA", "absolute"),
        0x9D: ("STA", "absolute_X"),
        0xAD: ("LDA", "absolute"),
        0xBD: ("LDA", "absolute_X"),
        0xCD: ("CMP", "absolute"),
        0xDD: ("CMP", "absolute_X"),
        0xED: ("SBC", "absolute"),
        0xFD: ("SBC", "absolute_X"),

        # Low nibble 0xE
        0x0E: ("ASL", "absolute"),
        0x1E: ("ASL", "absolute_X"),
        0x2E: ("ROL", "absolute"),
        0x3E: ("ROL", "absolute_X"),
        0x4E: ("LSR", "absolute"),
        0x5E: ("LSR", "absolute_X"),
        0x6E: ("ROR", "absolute"),
        0x7E: ("ROR", "absolute_X"),
        0x8E: ("STX", "absolute"),
        0x9E: ("STZ", "absolute_X"),
        0xAE: ("LDX", "absolute"),
        0xBE: ("LDX", "absolute_Y"),
        0xCE: ("DEC", "absolute"),
        0xDE: ("DEC", "absolute_X"),
        0xEE: ("INC", "absolute"),
        0xFE: ("INC", "absolute_X"),

        # Low nibble 0xF
        0x0F: ("BBR0", "relative"),
        0x1F: ("BBR1", "relative"),
        0x2F: ("BBR2", "relative"),
        0x3F: ("BBR3", "relative"),
        0x4F: ("BBR4", "relative"),
        0x5F: ("BBR5", "relative"),
        0x6F: ("BBR6", "relative"),
        0x7F: ("BBR7", "relative"),
        0x8F: ("BBS0", "relative"),
        0x9F: ("BBS1", "relative"),
        0xAF: ("BBS2", "relative"),
        0xBF: ("BBS3", "relative"),
        0xCF: ("BBS4", "relative"),
        0xDF: ("BBS5", "relative"),
        0xEF: ("BBS6", "relative"),
        0xFF: ("BBS7", "relative"),
    }
