[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/toml65"]

[project]
#dynamic = ["version"]

authors = [
    {name = "Slava Nikolsky", email = "auguz1108@gmail.com"}
]

maintainers = [
    {name = "Slava Nikolsky", email = "auguz1108@gmail.com"}
]

name = "toml-6502"
version = "0.3.0"
description = "Emulate 65c02 with TOML memory mapping"
keywords = ["6502", "65c02", "wdc65c02", "emulator", "toml", "virtual machine"]
classifiers = [
    "Development Status :: 4 - Beta",

    "Environment :: Console",

    "Intended Audience :: Developers",

    "Topic :: System :: Emulators",
    "Topic :: Education",
    "Topic :: Software Development :: Build Tools",

    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",

    "License :: Free for non-commercial use",

    "Natural Language :: English",

    "Operating System :: POSIX",
]

readme = "readme.md"
license = "LicenseRef-Gusza-Softwares"
license-files = ["LICENSE"]

dependencies = [
    "py65"
]
requires-python = ">= 3.8"

[project.scripts]
toml-6502 = "toml65.main:main"

[project.urls]
Repository = "https://github.com/gusza110811/toml-6502"
